version: '3'
services:
  woss-io:
    image: "gcr.io/woss-private/woss-io"
    restart: always
    expose:
        - "3000"
    ports:
      - "3000:3000"
    volumes:
        - .:/app
    environment:
     - VIRTUAL_HOST=woss.io.dev
    network_mode: "bridge"