# apiVersion: v1
# kind: Service
# metadata:
#   name: woss-io
#   labels:
#     run: woss-io
# spec:
#   selector:
#     app: woss-io
#   ports:
#     - protocol: TCP
#       targetPort: 3000
#       port: 80

# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: woss-io-ingress
# spec:
#   rules:
#   - host: woss.io
#     http:
#       paths:
#       - backend:
#           serviceName: woss-io-service
#           servicePort: 3000